name = "Coinfer"
uuid = "2494631e-bceb-4539-8821-5341beee86e1"
version = "0.0.2"
authors = ["withdata.io"]

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
TuringCallbacks = "ea0860ee-d0ef-45ef-82e6-cc37d6be2f9c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[sources]
AbstractMCMC = {rev = "multiple-chains", url = "https://github.com/vectorly-ai/AbstractMCMC.jl"}
TuringCallbacks = {rev = "multiple-chains", url = "https://github.com/vectorly-ai/TuringCallbacks.jl"}

[extensions]
CoinferAPIExt = ["CSV"]

[compat]
MLJModelInterface = "~1.10"
OnlineStats = "1.7.2"
OnlineStatsBase = "1.7.1"
